class Mover{
    location;
    velocity;
    constructor(){
        this.location=createVector(width/2,height/2)
        this.velocity=createVector(1,3)
    }
  display(){
      fill(42,54,62)
      ellipseMode(CENTER)
      ellipse(this.location.x,this.location.y,90,90)
  }  
   update(){
       this.location.add(this.velocity)
   } 
   checkEdges(){
       if(this.location.x>width){
           this.location.x=0
       }
       if(this.location.x<0){
           this.location.x=width
       }
       if(this.location.y>height){
        this.location.y=0
        }
        if(this.location.y<0){
            this.location.y=height
        }
   }
}